#!/usr/bin/env python3
"""Generate an asar patch that replaces the Capcom logo tiles with text.

The logo is stored uncompressed at $9E:C000 as a 12x3 grid of 4bpp tiles,
in row-major order.
"""

import argparse

FONT = {
    " ": ("........", "........", "........", "........",
          "........", "........", "........", "........"),
    "P": ("..####..", "..#...#.", "..#...#.", "..####..",
          "..#.....", "..#.....", "..#.....", "........"),
    "R": ("..####..", "..#...#.", "..#...#.", "..####..",
          "..#..#..", "..#...#.", "..#...#.", "........"),
    "A": ("...##...", "..#..#..", "..#..#..", "..####..",
          "..#..#..", "..#..#..", "..#..#..", "........"),
    "C": ("...###..", "..#...#.", "..#.....", "..#.....",
          "..#.....", "..#...#.", "...###..", "........"),
    "T": ("..#####.", "....#...", "....#...", "....#...",
          "....#...", "....#...", "....#...", "........"),
    "I": ("..#####.", "....#...", "....#...", "....#...",
          "....#...", "....#...", "..#####.", "........"),
    "E": ("..#####.", "..#.....", "..#.....", "..####..",
          "..#.....", "..#.....", "..#####.", "........"),
}

BOLD = {
    " ": ("........", "........", "........", "........",
          "........", "........", "........", "........"),
    "P": (".######.", ".##..##.", ".##..##.", ".######.",
          ".##.....", ".##.....", ".##.....", "........"),
    "R": (".######.", ".##..##.", ".##..##.", ".######.",
          ".##.##..", ".##..##.", ".##..##.", "........"),
    "A": ("..####..", ".##..##.", ".##..##.", ".######.",
          ".##..##.", ".##..##.", ".##..##.", "........"),
    "C": ("..#####.", ".##...#.", ".##.....", ".##.....",
          ".##.....", ".##...#.", "..#####.", "........"),
    "T": (".######.", "...##...", "...##...", "...##...",
          "...##...", "...##...", "...##...", "........"),
    "I": (".######.", "...##...", "...##...", "...##...",
          "...##...", "...##...", ".######.", "........"),
    "E": (".######.", ".##.....", ".##.....", ".#####..",
          ".##.....", ".##.....", ".######.", "........"),
}


def tall_rows(ch, rows):
    """Stretch an 8x8 glyph over `rows` tiles vertically (8*rows scanlines)."""
    src = BOLD[ch]
    total = 8 * rows
    return [src[(y * 8) // total] for y in range(total)]


def encode_4bpp(grid, ink):
    """Pack an 8x8 grid of palette indices into 32 bytes of SNES 4bpp."""
    out = bytearray(32)
    for y in range(8):
        for pl in range(4):
            group, within = divmod(pl, 2)
            idx = group * 16 + y * 2 + within
            byte = 0
            for x in range(8):
                v = ink if grid[y][x] == "#" else 0
                if (v >> pl) & 1:
                    byte |= 1 << (7 - x)
            out[idx] = byte
    return bytes(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--text", default="PRACTICE")
    ap.add_argument("--ink", type=int, default=13)
    ap.add_argument("--cols", type=int, default=12)
    ap.add_argument("--rows", type=int, default=3)
    ap.add_argument("--row", type=int, default=1, help="which tile row to draw on")
    ap.add_argument("--tall", action="store_true",
                    help="draw bold glyphs spanning every tile row")
    ap.add_argument("--addr", default="$9EC000")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    text = args.text.upper()
    table = BOLD if args.tall else FONT
    missing = sorted(set(text) - set(table))
    if missing:
        raise SystemExit(f"no glyph for: {' '.join(missing)}")
    if len(text) > args.cols:
        raise SystemExit(f"{len(text)} chars will not fit in {args.cols} tiles")

    pad = (args.cols - len(text)) // 2
    line = " " * pad + text
    line += " " * (args.cols - len(line))

    tiles = []
    if args.tall:
        stretched = {c: tall_rows(c, args.rows) for c in set(line)}
        for r in range(args.rows):
            for c in range(args.cols):
                band = stretched[line[c]][r * 8:(r + 1) * 8]
                tiles.append(encode_4bpp(band, args.ink))
    else:
        for r in range(args.rows):
            for c in range(args.cols):
                ch = line[c] if r == args.row else " "
                tiles.append(encode_4bpp(FONT[ch], args.ink))

    with open(args.out, "w") as f:
        f.write("; generated by tools/mkglyphs.py\n")
        f.write('incsrc "../../../build/rom_config.inc"\n\n')
        f.write(f"org {args.addr}\n")
        for i, t in enumerate(tiles):
            f.write(f"    ; tile {i}\n")
            for k in range(0, 32, 16):
                f.write("    db " + ",".join(f"${b:02X}" for b in t[k:k + 16]) + "\n")
    print(f"wrote {args.out}: {len(tiles)} tiles, text {line!r}, ink index {args.ink}")


if __name__ == "__main__":
    main()
