#!/usr/bin/env python3
"""Identify and validate a Demon's Crest / Demon's Blazon ROM."""

import argparse
import hashlib
import sys
from pathlib import Path

MAPPINGS = {
    0x20: ("lorom", "LoROM"),
    0x21: ("hirom", "HiROM"),
    0x23: ("lorom", "LoROM (SA-1)"),
    0x30: ("lorom", "LoROM + FastROM"),
    0x31: ("hirom", "HiROM + FastROM"),
    0x32: ("exlorom", "ExLoROM"),
    0x35: ("exhirom", "ExHiROM"),
}

CHIPSETS = {
    0x00: "ROM only",
    0x01: "ROM + RAM",
    0x02: "ROM + RAM + battery",
    0x03: "ROM + coprocessor",
    0x04: "ROM + coprocessor + RAM",
    0x05: "ROM + coprocessor + RAM + battery",
    0x06: "ROM + coprocessor + battery",
}

REGIONS = {0x00: "Japan", 0x01: "USA", 0x02: "Europe"}


def strip_copier_header(data):
    """Copier dumps prepend 512 bytes; real cart dumps are a whole number of KB."""
    if len(data) % 1024 == 512:
        return data[512:], True
    return data, False


def parse_header(data, base):
    h = data[base:base + 32]
    if len(h) < 32:
        return None
    checksum = int.from_bytes(h[0x1E:0x20], "little")
    complement = int.from_bytes(h[0x1C:0x1E], "little")
    return {
        "base": base,
        "title": h[0x00:0x15].decode("ascii", errors="replace").rstrip(" \x00"),
        "mapping_byte": h[0x15],
        "chipset": h[0x16],
        "rom_size_kb": 1 << h[0x17] if h[0x17] else 0,
        "sram_size_kb": 1 << h[0x18] if h[0x18] else 0,
        "region": h[0x19],
        "developer": h[0x1A],
        "version": h[0x1B],
        "checksum": checksum,
        "complement": complement,
        "checksum_valid": (checksum + complement) & 0xFFFF == 0xFFFF,
    }


def pick_header(data):
    """LoROM and HiROM put the header at different offsets; the valid checksum disambiguates."""
    candidates = [parse_header(data, off) for off in (0x7FC0, 0xFFC0, 0x40FFC0)]
    candidates = [c for c in candidates if c]
    valid = [c for c in candidates if c["checksum_valid"] and c["mapping_byte"] in MAPPINGS]
    if valid:
        return valid[0], candidates
    return None, candidates


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("rom", type=Path)
    ap.add_argument("--emit-config", type=Path, help="write asar include with the detected mapping")
    ap.add_argument("--lock", type=Path, help="compare SHA-1 against this lockfile, creating it if absent")
    args = ap.parse_args()

    if not args.rom.is_file():
        sys.exit(f"error: no such ROM: {args.rom}")

    raw = args.rom.read_bytes()
    data, had_copier = strip_copier_header(raw)
    sha1 = hashlib.sha1(data).hexdigest()

    hdr, tried = pick_header(data)

    print(f"file         {args.rom}")
    print(f"size         {len(raw):,} bytes" + (" (512-byte copier header stripped)" if had_copier else ""))
    print(f"sha1         {sha1}   [headerless]")

    if not hdr:
        print("\nheader       COULD NOT IDENTIFY", file=sys.stderr)
        for c in tried:
            print(f"  tried ${c['base']:06X}: mapping=${c['mapping_byte']:02X} "
                  f"checksum_ok={c['checksum_valid']} title={c['title']!r}", file=sys.stderr)
        sys.exit("error: not a recognizable SNES ROM, or an unusual mapping")

    directive, mapping_name = MAPPINGS[hdr["mapping_byte"]]
    print(f"header at    ${hdr['base']:06X}")
    print(f"title        {hdr['title']!r}")
    print(f"mapping      {mapping_name} (${hdr['mapping_byte']:02X}) -> asar `{directive}`")
    print(f"chipset      {CHIPSETS.get(hdr['chipset'], 'unknown')} (${hdr['chipset']:02X})")
    print(f"rom size     {hdr['rom_size_kb']} KB (header claim); actual {len(data) // 1024} KB")
    print(f"sram         {hdr['sram_size_kb']} KB")
    print(f"region       {REGIONS.get(hdr['region'], 'unknown')} (${hdr['region']:02X})")
    print(f"version      1.{hdr['version']}")
    print(f"checksum     ${hdr['checksum']:04X} / complement ${hdr['complement']:04X}  "
          f"{'OK' if hdr['checksum_valid'] else 'MISMATCH'}")

    problems = []
    if hdr["region"] != 0x00:
        problems.append(f"region is {REGIONS.get(hdr['region'], 'unknown')}, but this project targets Japan "
                        "(the RAM map in memory-map/README.md is JP-only)")
    if hdr["sram_size_kb"] == 0:
        problems.append("no SRAM reported, so practice config cannot persist across power cycles")
    if not hdr["checksum_valid"]:
        problems.append("internal checksum does not validate; the dump may be bad or already modified")

    if args.emit_config:
        args.emit_config.parent.mkdir(parents=True, exist_ok=True)
        args.emit_config.write_text(
            f"; generated by tools/romcheck.py -- do not edit\n"
            f"{directive}\n"
            f"!rom_size_kb = {len(data) // 1024}\n"
            f"!sram_size_kb = {hdr['sram_size_kb']}\n"
        )
        print(f"\nwrote        {args.emit_config}")

    if args.lock:
        if args.lock.exists():
            expected = args.lock.read_text().split()[0]
            if expected != sha1:
                sys.exit(f"\nerror: ROM does not match {args.lock}\n"
                         f"  expected {expected}\n  got      {sha1}")
            print(f"lock         matches {args.lock}")
        else:
            args.lock.write_text(f"{sha1}  {args.rom.name}\n")
            print(f"lock         created {args.lock} (pinning this dump for future builds)")

    if problems:
        print("\nWARNINGS")
        for p in problems:
            print(f"  - {p}")


if __name__ == "__main__":
    main()
